fix(2646): Do not include parameters from external builds during remote join
screwdriver-cd/launcher pull request #432
Opened 2022-02-17 17:47 UTC by sagar1312

## Context

Parameters from external builds are being included during remote join.

## Objective

Parameters must be available only to pipeline and its jobs. Parameters from external builds (jobs of another pipeline) should not be made available to the jobs during remote join.

## References

https://github.com/screwdriver-cd/screwdriver/issues/2646

## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2022-02-17 17:53 UTC, adong approved these changes

2022-02-18 18:01 UTC, adong approved these changes

2022-02-18 19:28 UTC, tkyi commented on launch.go
>  				resultMeta = deepMergeJSON(resultMeta, parentBuild.Meta)
is this what you meant to do?
```suggestion
				resultMeta = deepMergeJSON(resultMeta, externalParentBuildMeta)
```

2022-02-18 19:28 UTC, tkyi requested changes
don't think the change will work atm

2022-02-19 00:34 UTC, tkyi approved these changes

2022-02-22 17:23 UTC, merged